/*
 * File: VITALALL.c
 *
 * Code generated for Simulink model 'VITALALL'.
 *
 * Model version                  : 1.384
 * Simulink Coder version         : 8.9 (R2015b) 13-Aug-2015
 * C/C++ source code generated on : Fri Jun 16 08:26:37 2017
 *
 * Target selection: ert.tlc
 * Embedded hardware selection: Intel->x86-32 (Windows32)
 * Code generation objectives: Unspecified
 * Validation result: Not run
 */

#include "VITALALL.h"
#include "VITALALL_private.h"

rtTimingBridge VITALALL_TimingBrdg;

/* Block signals (auto storage) */
B_VITALALL_T VITALALL_B;

/* Block states (auto storage) */
DW_VITALALL_T VITALALL_DW;

/* External inputs (root inport signals with auto storage) */
ExtU_VITALALL_T VITALALL_U;

/* External outputs (root outports fed by signals with auto storage) */
ExtY_VITALALL_T VITALALL_Y;

/* Real-time model */
RT_MODEL_VITALALL_T VITALALL_M_;
RT_MODEL_VITALALL_T *const VITALALL_M = &VITALALL_M_;

/*
 * Output and update for atomic system:
 *    '<S46>/ROUTE LOGIC'
 *    '<S47>/ROUTE LOGIC'
 *    '<S48>/ROUTE LOGIC'
 *    '<S49>/ROUTE LOGIC'
 *    '<S51>/ROUTE LOGIC'
 *    '<S52>/ROUTE LOGIC'
 *    '<S53>/ROUTE LOGIC'
 *    '<S56>/ROUTE LOGIC'
 *    '<S58>/ROUTE LOGIC'
 *    '<S59>/ROUTE LOGIC'
 *    ...
 */
void ROUTE(boolean_T rtu_SIG, boolean_T rtu_PM1, boolean_T rtu_PM2, boolean_T
           rtu_PM3, boolean_T rtu_L, boolean_T rtu_RST, boolean_T rtu_RRLS,
           boolean_T rtu_TP, ConstB_ROUTE_T *localC, DW_ROUTE_T *localDW)
{
  boolean_T rtb_OR5;

  /* Logic: '<S67>/OR5' incorporates:
   *  Logic: '<S67>/OR3'
   *  Logic: '<S67>/OR4'
   *  Memory: '<S67>/Memory1'
   */
  rtb_OR5 = (((rtu_L && rtu_TP) || localDW->Memory1_PreviousInput) &&
             localC->NOT4);

  /* Update for Memory: '<S67>/Memory' incorporates:
   *  Logic: '<S67>/AND1'
   *  Logic: '<S67>/AND2'
   *  Logic: '<S67>/NOT1'
   *  Logic: '<S67>/NOT2'
   *  Logic: '<S67>/NOT3'
   *  Logic: '<S67>/OR1'
   *  Logic: '<S67>/OR2'
   *  Memory: '<S67>/Memory'
   */
  localDW->Memory_PreviousInput = ((localDW->Memory_PreviousInput || (rtu_SIG &&
    rtu_PM1 && rtu_PM2 && rtu_PM3)) && ((!rtu_L) || rtb_OR5) && (!rtu_RST) &&
    (!rtu_RRLS));

  /* Update for Memory: '<S67>/Memory1' */
  localDW->Memory1_PreviousInput = rtb_OR5;
}

/*
 * Output and update for atomic system:
 *    '<S50>/ROUTE LOGIC'
 *    '<S54>/ROUTE LOGIC'
 *    '<S55>/ROUTE LOGIC'
 *    '<S57>/ROUTE LOGIC'
 *    '<S60>/ROUTE LOGIC'
 *    '<S65>/ROUTE LOGIC'
 */
void VITALALL_ROUTE(boolean_T rtu_SIG, boolean_T rtu_PM1, boolean_T rtu_PM2,
                    boolean_T rtu_PM3, boolean_T rtu_L, boolean_T rtu_RST,
                    boolean_T rtu_RRLS, boolean_T rtu_TP, boolean_T rtu_FINISH,
                    B_ROUTE_g_T *localB, DW_ROUTE_k_T *localDW)
{
  boolean_T rtb_OR5;

  /* Memory: '<S71>/Memory' */
  localB->Memory = localDW->Memory_PreviousInput;

  /* Logic: '<S71>/OR5' incorporates:
   *  Logic: '<S71>/NOT4'
   *  Logic: '<S71>/OR3'
   *  Logic: '<S71>/OR4'
   *  Memory: '<S71>/Memory1'
   */
  rtb_OR5 = (((rtu_L && rtu_TP) || localDW->Memory1_PreviousInput) &&
             (!rtu_FINISH));

  /* Update for Memory: '<S71>/Memory' incorporates:
   *  Logic: '<S71>/AND1'
   *  Logic: '<S71>/AND2'
   *  Logic: '<S71>/NOT1'
   *  Logic: '<S71>/NOT2'
   *  Logic: '<S71>/NOT3'
   *  Logic: '<S71>/OR1'
   *  Logic: '<S71>/OR2'
   */
  localDW->Memory_PreviousInput = ((localB->Memory || (rtu_SIG && rtu_PM1 &&
    rtu_PM2 && rtu_PM3)) && ((!rtu_L) || rtb_OR5) && (!rtu_RST) && (!rtu_RRLS));

  /* Update for Memory: '<S71>/Memory1' */
  localDW->Memory1_PreviousInput = rtb_OR5;
}

/* Model step function */
void VITALALL_step(void)
{
  int32_T i;

  /* Memory: '<S11>/Memory' */
  VITALALL_B.Memory[0] = VITALALL_DW.Memory_PreviousInput[0];
  VITALALL_B.Memory[1] = VITALALL_DW.Memory_PreviousInput[1];
  VITALALL_B.Memory[2] = VITALALL_DW.Memory_PreviousInput[2];
  VITALALL_B.Memory[3] = VITALALL_DW.Memory_PreviousInput[3];

  /* Logic: '<S22>/AND' incorporates:
   *  Inport: '<Root>/INDEP'
   *  Inport: '<Root>/INT3'
   *  Inport: '<Root>/INTIB'
   */
  VITALALL_B.AND = (VITALALL_U.INTIB[0] && VITALALL_U.INT3[0] &&
                    VITALALL_U.INDEP[0]);

  /* SignalConversion: '<S11>/TmpSignal ConversionAtVITAL MAINLINEInport13' incorporates:
   *  Inport: '<Root>/DATAFROMZC'
   */
  for (i = 0; i < 13; i++) {
    VITALALL_B.TmpSignalConversionAtVITALMAINL[i] = VITALALL_U.DATAFROMZC[i + 14];
  }

  for (i = 0; i < 14; i++) {
    VITALALL_B.TmpSignalConversionAtVITALMAINL[i + 13] = VITALALL_U.DATAFROMZC[i];
  }

  /* End of SignalConversion: '<S11>/TmpSignal ConversionAtVITAL MAINLINEInport13' */

  /* SignalConversion: '<S11>/TmpSignal ConversionAtVITAL MAINLINEInport14' incorporates:
   *  Inport: '<Root>/INT3'
   *  Inport: '<Root>/INTIB'
   */
  VITALALL_B.TmpSignalConversionAtVITALMAI_a[0] = VITALALL_U.INTIB[2];
  VITALALL_B.TmpSignalConversionAtVITALMAI_a[1] = VITALALL_U.INTIB[4];
  VITALALL_B.TmpSignalConversionAtVITALMAI_a[2] = VITALALL_U.INTIB[6];
  VITALALL_B.TmpSignalConversionAtVITALMAI_a[3] = VITALALL_U.INT3[2];
  VITALALL_B.TmpSignalConversionAtVITALMAI_a[4] = VITALALL_U.INT3[4];

  /* SignalConversion: '<S11>/TmpSignal ConversionAtVITAL MAINLINEInport15' incorporates:
   *  Inport: '<Root>/INT3'
   *  Inport: '<Root>/INTIB'
   */
  VITALALL_B.TmpSignalConversionAtVITALMAI_l[0] = VITALALL_U.INTIB[3];
  VITALALL_B.TmpSignalConversionAtVITALMAI_l[1] = VITALALL_U.INTIB[5];
  VITALALL_B.TmpSignalConversionAtVITALMAI_l[2] = VITALALL_U.INTIB[7];
  VITALALL_B.TmpSignalConversionAtVITALMAI_l[3] = VITALALL_U.INT3[3];
  VITALALL_B.TmpSignalConversionAtVITALMAI_l[4] = VITALALL_U.INT3[5];

  /* ModelReference: '<S11>/VITAL MAINLINE' */
  VITALMAIN(&VITALALL_B.Memory[0], &VITALALL_U.DATAFROMNV[0],
            &VITALALL_U.DATAFROMNV[1], &VITALALL_U.DATAFROMNV[2],
            &VITALALL_U.DATAFROMNV[30], &VITALALL_U.DATAFROMNV[39],
            &VITALALL_U.DATAFROMNV[48], &VITALALL_U.DATAFROMNV[57],
            &VITALALL_U.DATAFROMNV[73], &VITALALL_U.DATAFROMNV[82],
            &VITALALL_U.DATAFROMNV[102], &VITALALL_B.AND,
            &VITALALL_B.TmpSignalConversionAtVITALMAINL[0],
            &VITALALL_B.TmpSignalConversionAtVITALMAI_a[0],
            &VITALALL_B.TmpSignalConversionAtVITALMAI_l[0],
            &VITALALL_B.VITALMAINLINE_o1[0], &VITALALL_B.VITALMAINLINE_o2,
            &VITALALL_B.VITALMAINLINE_o3, &VITALALL_B.VITALMAINLINE_o4[0],
            &VITALALL_B.VITALMAINLINE_o5[0], &VITALALL_B.VITALMAINLINE_o6[0],
            &VITALALL_B.VITALMAINLINE_o7[0], &VITALALL_B.VITALMAINLINE_o8[0],
            &VITALALL_B.VITALMAINLINE_o9[0], &VITALALL_B.VITALMAINLINE_o10[0],
            &VITALALL_B.VITALMAINLINE_o11[0], &VITALALL_B.VITALMAINLINE_o12[0],
            &VITALALL_B.VITALMAINLINE_o13[0], &VITALALL_B.VITALMAINLINE_o14[0],
            &VITALALL_B.VITALMAINLINE_o15[0], &VITALALL_B.VITALMAINLINE_o16[0],
            &VITALALL_B.VITALMAINLINE_o17[0], &VITALALL_B.VITALMAINLINE_o18[0],
            &VITALALL_B.VITALMAINLINE_o19[0], &VITALALL_B.VITALMAINLINE_o20[0],
            &VITALALL_B.VITALMAINLINE_o21[0], &VITALALL_B.VITALMAINLINE_o22[0],
            &VITALALL_B.VITALMAINLINE_o23[0], &VITALALL_B.VITALMAINLINE_o24[0],
            &VITALALL_B.VITALMAINLINE_o25[0], &VITALALL_B.VITALMAINLINE_o26,
            &VITALALL_B.VITALMAINLINE_o27[0], &VITALALL_B.VITALMAINLINE_o28[0],
            &VITALALL_B.VITALMAINLINE_o29[0], &VITALALL_B.VITALMAINLINE_o30[0],
            &VITALALL_B.VITALMAINLINE_o31[0]);

  /* SignalConversion: '<S11>/TmpSignal ConversionAtVITAL DEPOTInport10' incorporates:
   *  Inport: '<Root>/INDEP'
   */
  VITALALL_B.TmpSignalConversionAtVITALDEPOT[0] = VITALALL_U.INDEP[16];
  VITALALL_B.TmpSignalConversionAtVITALDEPOT[1] = VITALALL_U.INDEP[48];
  VITALALL_B.TmpSignalConversionAtVITALDEPOT[2] = VITALALL_U.INDEP[56];
  VITALALL_B.TmpSignalConversionAtVITALDEPOT[3] = VITALALL_U.INDEP[17];
  VITALALL_B.TmpSignalConversionAtVITALDEPOT[4] = VITALALL_U.INDEP[20];
  VITALALL_B.TmpSignalConversionAtVITALDEPOT[5] = VITALALL_U.INDEP[21];
  VITALALL_B.TmpSignalConversionAtVITALDEPOT[6] = VITALALL_U.INDEP[18];
  VITALALL_B.TmpSignalConversionAtVITALDEPOT[7] = VITALALL_U.INDEP[52];
  VITALALL_B.TmpSignalConversionAtVITALDEPOT[8] = VITALALL_U.INDEP[32];
  VITALALL_B.TmpSignalConversionAtVITALDEPOT[9] = VITALALL_U.INDEP[22];

  /* SignalConversion: '<S11>/TmpSignal ConversionAtVITAL DEPOTInport11' incorporates:
   *  Inport: '<Root>/INDEP'
   */
  VITALALL_B.TmpSignalConversionAtVITALDEP_b[0] = VITALALL_U.INDEP[64];
  VITALALL_B.TmpSignalConversionAtVITALDEP_b[1] = VITALALL_U.INDEP[72];
  VITALALL_B.TmpSignalConversionAtVITALDEP_b[2] = VITALALL_U.INDEP[66];
  VITALALL_B.TmpSignalConversionAtVITALDEP_b[3] = VITALALL_U.INDEP[68];

  /* SignalConversion: '<S11>/TmpSignal ConversionAtVITAL DEPOTInport12' incorporates:
   *  Inport: '<Root>/INDEP'
   */
  VITALALL_B.TmpSignalConversionAtVITALDEP_f[0] = VITALALL_U.INDEP[65];
  VITALALL_B.TmpSignalConversionAtVITALDEP_f[1] = VITALALL_U.INDEP[73];
  VITALALL_B.TmpSignalConversionAtVITALDEP_f[2] = VITALALL_U.INDEP[67];
  VITALALL_B.TmpSignalConversionAtVITALDEP_f[3] = VITALALL_U.INDEP[69];

  /* ModelReference: '<S11>/VITAL DEPOT' */
  VITALDEPOT(&VITALALL_B.VITALMAINLINE_o1[0], &VITALALL_U.DATAFROMNV[18],
             &VITALALL_U.DATAFROMNV[35], &VITALALL_U.DATAFROMNV[44],
             &VITALALL_U.DATAFROMNV[53], &VITALALL_U.DATAFROMNV[65],
             &VITALALL_U.DATAFROMNV[78], &VITALALL_U.DATAFROMNV[90],
             &VITALALL_U.DATAFROMNV[111],
             &VITALALL_B.TmpSignalConversionAtVITALDEPOT[0],
             &VITALALL_B.TmpSignalConversionAtVITALDEP_b[0],
             &VITALALL_B.TmpSignalConversionAtVITALDEP_f[0],
             &VITALALL_B.VITALDEPOT_o1[0], &VITALALL_B.VITALDEPOT_o2[0],
             &VITALALL_B.VITALDEPOT_o3[0], &VITALALL_B.VITALDEPOT_o4[0],
             &VITALALL_B.VITALDEPOT_o5[0], &VITALALL_B.VITALDEPOT_o6[0],
             &VITALALL_B.VITALDEPOT_o7[0], &VITALALL_B.VITALDEPOT_o8[0],
             &VITALALL_B.VITALDEPOT_o9[0], &VITALALL_B.VITALDEPOT_o10[0],
             &VITALALL_B.VITALDEPOT_o11[0], &VITALALL_B.VITALDEPOT_o12[0],
             &VITALALL_B.VITALDEPOT_o13[0], &VITALALL_B.VITALDEPOT_o14[0],
             &VITALALL_B.VITALDEPOT_o15[0], &VITALALL_B.VITALDEPOT_o16[0],
             &VITALALL_B.VITALDEPOT_o17[0], &VITALALL_B.VITALDEPOT_o18[0],
             &VITALALL_B.VITALDEPOT_o19[0], &VITALALL_B.VITALDEPOT_o20[0],
             &VITALALL_B.VITALDEPOT_o21[0], &VITALALL_B.VITALDEPOT_o22[0],
             &VITALALL_B.VITALDEPOT_o23[0]);

  /* Outport: '<Root>/DATATONV' incorporates:
   *  Inport: '<Root>/CBISYSTEM'
   *  Inport: '<Root>/INDEP'
   *  Inport: '<Root>/INT1'
   *  Inport: '<Root>/INT2'
   *  Inport: '<Root>/INT3'
   *  Inport: '<Root>/INTIB'
   */
  VITALALL_Y.DATATONV[0] = VITALALL_B.VITALMAINLINE_o2;
  VITALALL_Y.DATATONV[1] = VITALALL_B.VITALMAINLINE_o3;
  for (i = 0; i < 27; i++) {
    VITALALL_Y.DATATONV[i + 2] = VITALALL_B.VITALMAINLINE_o4[i];
  }

  for (i = 0; i < 10; i++) {
    VITALALL_Y.DATATONV[i + 29] = VITALALL_B.VITALDEPOT_o2[i];
  }

  for (i = 0; i < 21; i++) {
    VITALALL_Y.DATATONV[i + 39] = VITALALL_B.VITALMAINLINE_o5[i];
    VITALALL_Y.DATATONV[i + 60] = VITALALL_B.VITALMAINLINE_o6[i];
  }

  VITALALL_Y.DATATONV[88] = VITALALL_B.VITALDEPOT_o3[0];
  VITALALL_Y.DATATONV[89] = VITALALL_B.VITALDEPOT_o3[1];
  VITALALL_Y.DATATONV[90] = VITALALL_B.VITALDEPOT_o3[2];
  for (i = 0; i < 7; i++) {
    VITALALL_Y.DATATONV[i + 81] = VITALALL_B.VITALMAINLINE_o7[i];
    VITALALL_Y.DATATONV[i + 91] = VITALALL_B.VITALMAINLINE_o8[i];
  }

  VITALALL_Y.DATATONV[98] = VITALALL_B.VITALDEPOT_o4[0];
  VITALALL_Y.DATATONV[99] = VITALALL_B.VITALDEPOT_o4[1];
  VITALALL_Y.DATATONV[100] = VITALALL_B.VITALDEPOT_o4[2];
  VITALALL_Y.DATATONV[106] = VITALALL_B.VITALDEPOT_o5[0];
  VITALALL_Y.DATATONV[107] = VITALALL_B.VITALDEPOT_o5[1];
  VITALALL_Y.DATATONV[108] = VITALALL_B.VITALDEPOT_o5[2];
  VITALALL_Y.DATATONV[109] = VITALALL_B.VITALDEPOT_o5[3];
  VITALALL_Y.DATATONV[115] = VITALALL_B.VITALDEPOT_o6[0];
  VITALALL_Y.DATATONV[116] = VITALALL_B.VITALDEPOT_o6[1];
  VITALALL_Y.DATATONV[117] = VITALALL_B.VITALDEPOT_o6[2];
  VITALALL_Y.DATATONV[118] = VITALALL_B.VITALDEPOT_o6[3];
  VITALALL_Y.DATATONV[124] = VITALALL_B.VITALDEPOT_o7[0];
  VITALALL_Y.DATATONV[125] = VITALALL_B.VITALDEPOT_o7[1];
  VITALALL_Y.DATATONV[126] = VITALALL_B.VITALDEPOT_o7[2];
  VITALALL_Y.DATATONV[127] = VITALALL_B.VITALDEPOT_o7[3];
  VITALALL_Y.DATATONV[133] = VITALALL_B.VITALDEPOT_o8[0];
  VITALALL_Y.DATATONV[134] = VITALALL_B.VITALDEPOT_o8[1];
  VITALALL_Y.DATATONV[135] = VITALALL_B.VITALDEPOT_o8[2];
  VITALALL_Y.DATATONV[136] = VITALALL_B.VITALDEPOT_o8[3];
  VITALALL_Y.DATATONV[142] = VITALALL_B.VITALDEPOT_o9[0];
  VITALALL_Y.DATATONV[143] = VITALALL_B.VITALDEPOT_o9[1];
  VITALALL_Y.DATATONV[144] = VITALALL_B.VITALDEPOT_o9[2];
  VITALALL_Y.DATATONV[145] = VITALALL_B.VITALDEPOT_o9[3];
  VITALALL_Y.DATATONV[151] = VITALALL_B.VITALDEPOT_o10[0];
  VITALALL_Y.DATATONV[152] = VITALALL_B.VITALDEPOT_o10[1];
  VITALALL_Y.DATATONV[153] = VITALALL_B.VITALDEPOT_o10[2];
  VITALALL_Y.DATATONV[154] = VITALALL_B.VITALDEPOT_o10[3];
  VITALALL_Y.DATATONV[160] = VITALALL_B.VITALDEPOT_o11[0];
  VITALALL_Y.DATATONV[161] = VITALALL_B.VITALDEPOT_o11[1];
  VITALALL_Y.DATATONV[162] = VITALALL_B.VITALDEPOT_o11[2];
  VITALALL_Y.DATATONV[163] = VITALALL_B.VITALDEPOT_o11[3];
  VITALALL_Y.DATATONV[169] = VITALALL_B.VITALDEPOT_o12[0];
  VITALALL_Y.DATATONV[170] = VITALALL_B.VITALDEPOT_o12[1];
  VITALALL_Y.DATATONV[171] = VITALALL_B.VITALDEPOT_o12[2];
  VITALALL_Y.DATATONV[172] = VITALALL_B.VITALDEPOT_o12[3];
  VITALALL_Y.DATATONV[178] = VITALALL_B.VITALDEPOT_o13[0];
  VITALALL_Y.DATATONV[179] = VITALALL_B.VITALDEPOT_o13[1];
  VITALALL_Y.DATATONV[180] = VITALALL_B.VITALDEPOT_o13[2];
  VITALALL_Y.DATATONV[181] = VITALALL_B.VITALDEPOT_o13[3];
  VITALALL_Y.DATATONV[187] = VITALALL_B.VITALDEPOT_o14[0];
  VITALALL_Y.DATATONV[188] = VITALALL_B.VITALDEPOT_o14[1];
  VITALALL_Y.DATATONV[189] = VITALALL_B.VITALDEPOT_o14[2];
  VITALALL_Y.DATATONV[190] = VITALALL_B.VITALDEPOT_o14[3];
  VITALALL_Y.DATATONV[196] = VITALALL_B.VITALDEPOT_o15[0];
  VITALALL_Y.DATATONV[197] = VITALALL_B.VITALDEPOT_o15[1];
  VITALALL_Y.DATATONV[198] = VITALALL_B.VITALDEPOT_o15[2];
  VITALALL_Y.DATATONV[199] = VITALALL_B.VITALDEPOT_o15[3];
  for (i = 0; i < 5; i++) {
    VITALALL_Y.DATATONV[i + 101] = VITALALL_B.VITALMAINLINE_o9[i];
    VITALALL_Y.DATATONV[i + 110] = VITALALL_B.VITALMAINLINE_o10[i];
    VITALALL_Y.DATATONV[i + 119] = VITALALL_B.VITALMAINLINE_o11[i];
    VITALALL_Y.DATATONV[i + 128] = VITALALL_B.VITALMAINLINE_o12[i];
    VITALALL_Y.DATATONV[i + 137] = VITALALL_B.VITALMAINLINE_o13[i];
    VITALALL_Y.DATATONV[i + 146] = VITALALL_B.VITALMAINLINE_o14[i];
    VITALALL_Y.DATATONV[i + 155] = VITALALL_B.VITALMAINLINE_o15[i];
    VITALALL_Y.DATATONV[i + 164] = VITALALL_B.VITALMAINLINE_o16[i];
    VITALALL_Y.DATATONV[i + 173] = VITALALL_B.VITALMAINLINE_o17[i];
    VITALALL_Y.DATATONV[i + 182] = VITALALL_B.VITALMAINLINE_o18[i];
    VITALALL_Y.DATATONV[i + 191] = VITALALL_B.VITALMAINLINE_o19[i];
    VITALALL_Y.DATATONV[i + 200] = VITALALL_B.VITALMAINLINE_o20[i];
  }

  VITALALL_Y.DATATONV[205] = VITALALL_B.VITALDEPOT_o16[0];
  VITALALL_Y.DATATONV[206] = VITALALL_B.VITALDEPOT_o16[1];
  VITALALL_Y.DATATONV[207] = VITALALL_B.VITALDEPOT_o16[2];
  VITALALL_Y.DATATONV[208] = VITALALL_B.VITALDEPOT_o16[3];
  VITALALL_Y.DATATONV[217] = VITALALL_B.VITALMAINLINE_o22[0];
  VITALALL_Y.DATATONV[218] = VITALALL_B.VITALMAINLINE_o22[1];
  VITALALL_Y.DATATONV[235] = VITALALL_B.VITALMAINLINE_o24[0];
  VITALALL_Y.DATATONV[236] = VITALALL_B.VITALMAINLINE_o24[1];
  for (i = 0; i < 8; i++) {
    VITALALL_Y.DATATONV[i + 209] = VITALALL_B.VITALMAINLINE_o21[i];
    VITALALL_Y.DATATONV[i + 219] = VITALALL_B.VITALDEPOT_o17[i];
    VITALALL_Y.DATATONV[i + 227] = VITALALL_B.VITALMAINLINE_o23[i];
    VITALALL_Y.DATATONV[i + 237] = VITALALL_B.VITALDEPOT_o18[i];
    VITALALL_Y.DATATONV[i + 245] = VITALALL_B.VITALMAINLINE_o25[i];
    VITALALL_Y.DATATONV[i + 253] = VITALALL_B.VITALDEPOT_o19[i];
  }

  VITALALL_Y.DATATONV[261] = VITALALL_U.INT1[2];
  VITALALL_Y.DATATONV[262] = VITALALL_U.INT1[10];
  VITALALL_Y.DATATONV[263] = VITALALL_U.INTIB[18];
  VITALALL_Y.DATATONV[264] = VITALALL_U.INTIB[26];
  VITALALL_Y.DATATONV[265] = VITALALL_U.INT2[2];
  VITALALL_Y.DATATONV[266] = VITALALL_U.INT2[10];
  VITALALL_Y.DATATONV[267] = VITALALL_U.INT3[10];
  VITALALL_Y.DATATONV[268] = VITALALL_U.INT3[27];
  VITALALL_Y.DATATONV[269] = VITALALL_U.INT1[5];
  VITALALL_Y.DATATONV[270] = VITALALL_U.INT1[13];
  VITALALL_Y.DATATONV[271] = VITALALL_U.INTIB[21];
  VITALALL_Y.DATATONV[272] = VITALALL_U.INTIB[29];
  VITALALL_Y.DATATONV[273] = VITALALL_U.INT2[5];
  VITALALL_Y.DATATONV[274] = VITALALL_U.INT2[13];
  VITALALL_Y.DATATONV[275] = VITALALL_U.INT3[22];
  VITALALL_Y.DATATONV[276] = VITALALL_U.INT3[29];
  VITALALL_Y.DATATONV[277] = VITALALL_U.INT1[6];
  VITALALL_Y.DATATONV[279] = VITALALL_U.INT1[14];
  VITALALL_Y.DATATONV[281] = VITALALL_U.INTIB[22];
  VITALALL_Y.DATATONV[283] = VITALALL_U.INTIB[30];
  VITALALL_Y.DATATONV[285] = VITALALL_U.INT2[6];
  VITALALL_Y.DATATONV[287] = VITALALL_U.INT2[14];
  VITALALL_Y.DATATONV[289] = VITALALL_U.INT3[23];
  VITALALL_Y.DATATONV[291] = VITALALL_U.INT3[30];
  VITALALL_Y.DATATONV[278] = VITALALL_U.INT1[7];
  VITALALL_Y.DATATONV[280] = VITALALL_U.INT1[15];
  VITALALL_Y.DATATONV[282] = VITALALL_U.INTIB[23];
  VITALALL_Y.DATATONV[284] = VITALALL_U.INTIB[31];
  VITALALL_Y.DATATONV[286] = VITALALL_U.INT2[7];
  VITALALL_Y.DATATONV[288] = VITALALL_U.INT2[15];
  VITALALL_Y.DATATONV[290] = VITALALL_U.INT3[24];
  VITALALL_Y.DATATONV[292] = VITALALL_U.INT3[31];
  VITALALL_Y.DATATONV[293] = VITALALL_U.INDEP[74];
  VITALALL_Y.DATATONV[294] = VITALALL_U.CBISYSTEM[0];
  VITALALL_Y.DATATONV[295] = VITALALL_U.CBISYSTEM[1];
  VITALALL_Y.DATATONV[296] = VITALALL_U.CBISYSTEM[2];
  VITALALL_Y.DATATONV[297] = VITALALL_U.CBISYSTEM[3];

  /* End of Outport: '<Root>/DATATONV' */

  /* Outputs for Atomic SubSystem: '<S55>/ROUTE LOGIC' */

  /* Inport: '<Root>/INTIB' incorporates:
   *  Constant: '<S5>/ONE'
   *  Inport: '<Root>/DATAFROMNV'
   *  Inport: '<Root>/DATAFROMZC'
   */
  VITALALL_ROUTE(VITALALL_B.VITALMAINLINE_o27[1], VITALALL_U.INTIB[3],
                 VITALALL_U.INTIB[4], true, VITALALL_B.VITALMAINLINE_o5[6],
                 VITALALL_U.DATAFROMNV[135], VITALALL_B.VITALMAINLINE_o25[4],
                 VITALALL_U.DATAFROMZC[22], VITALALL_U.DATAFROMZC[43],
                 &VITALALL_B.ROUTELOGIC, &VITALALL_DW.ROUTELOGIC);

  /* End of Outputs for SubSystem: '<S55>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S50>/ROUTE LOGIC' */

  /* Inport: '<Root>/INT3' incorporates:
   *  Constant: '<S5>/ONE'
   *  Inport: '<Root>/DATAFROMNV'
   *  Inport: '<Root>/DATAFROMZC'
   */
  VITALALL_ROUTE(VITALALL_B.VITALMAINLINE_o27[4], VITALALL_U.INT3[2],
                 VITALALL_U.INT3[4], true, VITALALL_B.VITALMAINLINE_o5[9],
                 VITALALL_U.DATAFROMNV[138], VITALALL_B.VITALMAINLINE_o25[6],
                 VITALALL_U.DATAFROMZC[26], VITALALL_U.DATAFROMZC[44],
                 &VITALALL_B.ROUTELOGIC_c, &VITALALL_DW.ROUTELOGIC_c);

  /* End of Outputs for SubSystem: '<S50>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S54>/ROUTE LOGIC' */
  VITALALL_ROUTE(VITALALL_B.VITALMAINLINE_o27[6], VITALALL_U.INT3[2],
                 VITALALL_U.INT3[5], true, VITALALL_B.VITALMAINLINE_o6[14],
                 VITALALL_U.DATAFROMNV[140], VITALALL_B.VITALMAINLINE_o25[3],
                 VITALALL_U.DATAFROMZC[5], VITALALL_U.DATAFROMZC[45],
                 &VITALALL_B.ROUTELOGIC_i, &VITALALL_DW.ROUTELOGIC_i);

  /* End of Outputs for SubSystem: '<S54>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S60>/ROUTE LOGIC' */

  /* Inport: '<Root>/INTIB' incorporates:
   *  Inport: '<Root>/DATAFROMNV'
   *  Inport: '<Root>/DATAFROMZC'
   *  Inport: '<Root>/INDEP'
   */
  VITALALL_ROUTE(VITALALL_B.VITALMAINLINE_o27[3], VITALALL_U.INTIB[2],
                 VITALALL_U.INTIB[4], VITALALL_U.INTIB[6],
                 VITALALL_B.VITALMAINLINE_o6[10], VITALALL_U.DATAFROMNV[137],
                 VITALALL_B.VITALMAINLINE_o25[1], VITALALL_U.DATAFROMZC[0],
                 VITALALL_U.DATAFROMZC[46], &VITALALL_B.ROUTELOGIC_d,
                 &VITALALL_DW.ROUTELOGIC_d);

  /* End of Outputs for SubSystem: '<S60>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S57>/ROUTE LOGIC' */
  VITALALL_ROUTE(VITALALL_B.VITALMAINLINE_o28[1], VITALALL_U.INTIB[2],
                 VITALALL_U.INTIB[4], VITALALL_U.INTIB[7],
                 VITALALL_B.VITALMAINLINE_o7[6], VITALALL_U.DATAFROMNV[135],
                 VITALALL_B.VITALDEPOT_o19[6], VITALALL_U.INDEP[56],
                 VITALALL_U.DATAFROMZC[48], &VITALALL_B.ROUTELOGIC_b,
                 &VITALALL_DW.ROUTELOGIC_b);

  /* End of Outputs for SubSystem: '<S57>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S65>/ROUTE LOGIC' */
  VITALALL_ROUTE(VITALALL_B.VITALDEPOT_o20[7], VITALALL_U.INTIB[2],
                 VITALALL_U.INTIB[4], VITALALL_U.INTIB[7],
                 VITALALL_B.VITALMAINLINE_o8[3], VITALALL_U.DATAFROMNV[142],
                 VITALALL_B.VITALMAINLINE_o25[1], VITALALL_U.INDEP[56],
                 VITALALL_U.DATAFROMZC[47], &VITALALL_B.ROUTELOGIC_bp,
                 &VITALALL_DW.ROUTELOGIC_bp);

  /* End of Outputs for SubSystem: '<S65>/ROUTE LOGIC' */

  /* Outport: '<Root>/DATATOZC' incorporates:
   *  Inport: '<Root>/DATAFROMNV'
   *  Inport: '<Root>/INT1'
   *  Inport: '<Root>/INT2'
   *  Inport: '<Root>/INT3'
   *  Inport: '<Root>/INTIB'
   */
  VITALALL_Y.DATATOZC[0] = VITALALL_B.ROUTELOGIC.Memory;
  VITALALL_Y.DATATOZC[1] = VITALALL_B.ROUTELOGIC_c.Memory;
  VITALALL_Y.DATATOZC[2] = VITALALL_B.ROUTELOGIC_i.Memory;
  VITALALL_Y.DATATOZC[3] = VITALALL_B.ROUTELOGIC_d.Memory;
  VITALALL_Y.DATATOZC[4] = VITALALL_B.ROUTELOGIC_b.Memory;
  VITALALL_Y.DATATOZC[5] = VITALALL_B.ROUTELOGIC_bp.Memory;
  VITALALL_Y.DATATOZC[6] = VITALALL_U.DATAFROMNV[64];
  VITALALL_Y.DATATOZC[8] = VITALALL_U.DATAFROMNV[64];
  VITALALL_Y.DATATOZC[10] = VITALALL_U.DATAFROMNV[67];
  VITALALL_Y.DATATOZC[12] = VITALALL_U.DATAFROMNV[67];
  VITALALL_Y.DATATOZC[7] = VITALALL_U.DATAFROMNV[65];
  VITALALL_Y.DATATOZC[9] = VITALALL_U.DATAFROMNV[65];
  VITALALL_Y.DATATOZC[11] = VITALALL_U.DATAFROMNV[68];
  VITALALL_Y.DATATOZC[13] = VITALALL_U.DATAFROMNV[68];
  VITALALL_Y.DATATOZC[14] = VITALALL_U.DATAFROMNV[66];
  VITALALL_Y.DATATOZC[15] = VITALALL_U.INT1[2];
  VITALALL_Y.DATATOZC[16] = VITALALL_U.INT1[10];
  VITALALL_Y.DATATOZC[17] = VITALALL_U.INTIB[18];
  VITALALL_Y.DATATOZC[18] = VITALALL_U.INTIB[26];
  VITALALL_Y.DATATOZC[19] = VITALALL_U.INT2[2];
  VITALALL_Y.DATATOZC[20] = VITALALL_U.INT2[10];
  VITALALL_Y.DATATOZC[21] = VITALALL_U.INT3[10];
  VITALALL_Y.DATATOZC[22] = VITALALL_U.INT3[27];
  VITALALL_Y.DATATOZC[23] = VITALALL_U.INT1[5];
  VITALALL_Y.DATATOZC[24] = VITALALL_U.INT1[13];
  VITALALL_Y.DATATOZC[25] = VITALALL_U.INTIB[21];
  VITALALL_Y.DATATOZC[26] = VITALALL_U.INTIB[29];
  VITALALL_Y.DATATOZC[27] = VITALALL_U.INT2[5];
  VITALALL_Y.DATATOZC[28] = VITALALL_U.INT2[13];
  VITALALL_Y.DATATOZC[29] = VITALALL_U.INT3[22];
  VITALALL_Y.DATATOZC[30] = VITALALL_U.INT3[29];
  for (i = 0; i < 32; i++) {
    VITALALL_Y.DATATOZC[i + 31] = VITALALL_U.DATAFROMNV[i + 118];
  }

  VITALALL_Y.DATATOZC[63] = VITALALL_U.INT1[0];
  VITALALL_Y.DATATOZC[64] = VITALALL_U.INT1[8];
  VITALALL_Y.DATATOZC[65] = VITALALL_U.INTIB[16];
  VITALALL_Y.DATATOZC[66] = VITALALL_U.INTIB[24];
  VITALALL_Y.DATATOZC[67] = VITALALL_U.INT2[0];
  VITALALL_Y.DATATOZC[68] = VITALALL_U.INT2[8];
  VITALALL_Y.DATATOZC[69] = VITALALL_U.INT3[8];
  VITALALL_Y.DATATOZC[70] = VITALALL_U.INT3[25];
  VITALALL_Y.DATATOZC[71] = VITALALL_U.INT1[1];
  VITALALL_Y.DATATOZC[72] = VITALALL_U.INT1[9];
  VITALALL_Y.DATATOZC[73] = VITALALL_U.INTIB[17];
  VITALALL_Y.DATATOZC[74] = VITALALL_U.INTIB[25];
  VITALALL_Y.DATATOZC[75] = VITALALL_U.INT2[1];
  VITALALL_Y.DATATOZC[76] = VITALALL_U.INT2[9];
  VITALALL_Y.DATATOZC[77] = VITALALL_U.INT3[9];
  VITALALL_Y.DATATOZC[78] = VITALALL_U.INT3[26];
  VITALALL_Y.DATATOZC[79] = VITALALL_U.INT1[3];
  VITALALL_Y.DATATOZC[80] = VITALALL_U.INT1[11];
  VITALALL_Y.DATATOZC[81] = VITALALL_U.INTIB[19];
  VITALALL_Y.DATATOZC[82] = VITALALL_U.INTIB[27];
  VITALALL_Y.DATATOZC[83] = VITALALL_U.INT2[3];
  VITALALL_Y.DATATOZC[84] = VITALALL_U.INT2[11];
  VITALALL_Y.DATATOZC[85] = VITALALL_U.INT3[11];
  VITALALL_Y.DATATOZC[86] = VITALALL_U.INT3[28];

  /* End of Outport: '<Root>/DATATOZC' */

  /* Outport: '<Root>/OUTT1' incorporates:
   *  Constant: '<S5>/ZERO'
   *  Inport: '<Root>/DATAFROMZC'
   */
  VITALALL_Y.OUTT1[0] = VITALALL_U.DATAFROMZC[27];
  VITALALL_Y.OUTT1[1] = VITALALL_U.DATAFROMZC[35];
  VITALALL_Y.OUTT1[2] = false;
  VITALALL_Y.OUTT1[3] = false;
  VITALALL_Y.OUTT1[4] = VITALALL_U.DATAFROMZC[28];
  VITALALL_Y.OUTT1[5] = VITALALL_U.DATAFROMZC[36];
  VITALALL_Y.OUTT1[6] = false;
  VITALALL_Y.OUTT1[7] = false;

  /* Outport: '<Root>/OUTTIB' incorporates:
   *  Constant: '<S5>/ZERO'
   *  Inport: '<Root>/DATAFROMZC'
   */
  VITALALL_Y.OUTTIB[0] = VITALALL_B.VITALMAINLINE_o26;
  VITALALL_Y.OUTTIB[1] = false;
  VITALALL_Y.OUTTIB[2] = false;
  VITALALL_Y.OUTTIB[3] = false;
  VITALALL_Y.OUTTIB[4] = false;
  VITALALL_Y.OUTTIB[5] = false;
  VITALALL_Y.OUTTIB[6] = false;
  VITALALL_Y.OUTTIB[7] = false;
  VITALALL_Y.OUTTIB[8] = VITALALL_B.VITALMAINLINE_o30[0];
  VITALALL_Y.OUTTIB[9] = VITALALL_B.VITALMAINLINE_o29[0];
  VITALALL_Y.OUTTIB[10] = VITALALL_B.VITALMAINLINE_o30[0];
  VITALALL_Y.OUTTIB[11] = VITALALL_B.VITALMAINLINE_o29[0];
  VITALALL_Y.OUTTIB[12] = VITALALL_B.VITALMAINLINE_o30[1];
  VITALALL_Y.OUTTIB[13] = VITALALL_B.VITALMAINLINE_o29[1];
  VITALALL_Y.OUTTIB[14] = VITALALL_B.VITALMAINLINE_o30[1];
  VITALALL_Y.OUTTIB[15] = VITALALL_B.VITALMAINLINE_o29[1];
  VITALALL_Y.OUTTIB[16] = VITALALL_B.VITALMAINLINE_o30[2];
  VITALALL_Y.OUTTIB[17] = VITALALL_B.VITALMAINLINE_o29[2];
  VITALALL_Y.OUTTIB[18] = false;
  VITALALL_Y.OUTTIB[19] = false;
  VITALALL_Y.OUTTIB[20] = false;
  VITALALL_Y.OUTTIB[21] = false;
  VITALALL_Y.OUTTIB[22] = false;
  VITALALL_Y.OUTTIB[23] = false;
  VITALALL_Y.OUTTIB[24] = VITALALL_U.DATAFROMZC[29];
  VITALALL_Y.OUTTIB[25] = VITALALL_U.DATAFROMZC[37];
  VITALALL_Y.OUTTIB[26] = false;
  VITALALL_Y.OUTTIB[27] = false;
  VITALALL_Y.OUTTIB[28] = VITALALL_U.DATAFROMZC[30];
  VITALALL_Y.OUTTIB[29] = VITALALL_U.DATAFROMZC[38];
  VITALALL_Y.OUTTIB[30] = false;
  VITALALL_Y.OUTTIB[31] = false;

  /* Outport: '<Root>/OUTT2' incorporates:
   *  Constant: '<S5>/ZERO'
   *  Inport: '<Root>/DATAFROMZC'
   */
  VITALALL_Y.OUTT2[0] = VITALALL_U.DATAFROMZC[31];
  VITALALL_Y.OUTT2[1] = VITALALL_U.DATAFROMZC[39];
  VITALALL_Y.OUTT2[2] = false;
  VITALALL_Y.OUTT2[3] = false;
  VITALALL_Y.OUTT2[4] = VITALALL_U.DATAFROMZC[32];
  VITALALL_Y.OUTT2[5] = VITALALL_U.DATAFROMZC[40];
  VITALALL_Y.OUTT2[6] = false;
  VITALALL_Y.OUTT2[7] = false;

  /* Outport: '<Root>/OUTT3' incorporates:
   *  Constant: '<S5>/ZERO'
   *  Inport: '<Root>/DATAFROMZC'
   */
  VITALALL_Y.OUTT3[0] = VITALALL_B.VITALMAINLINE_o30[3];
  VITALALL_Y.OUTT3[1] = VITALALL_B.VITALMAINLINE_o29[3];
  VITALALL_Y.OUTT3[2] = VITALALL_B.VITALMAINLINE_o30[3];
  VITALALL_Y.OUTT3[3] = VITALALL_B.VITALMAINLINE_o29[3];
  VITALALL_Y.OUTT3[4] = VITALALL_B.VITALMAINLINE_o30[4];
  VITALALL_Y.OUTT3[5] = VITALALL_B.VITALMAINLINE_o29[4];
  VITALALL_Y.OUTT3[6] = VITALALL_B.VITALMAINLINE_o30[4];
  VITALALL_Y.OUTT3[7] = VITALALL_B.VITALMAINLINE_o29[4];
  VITALALL_Y.OUTT3[8] = VITALALL_B.VITALMAINLINE_o26;
  VITALALL_Y.OUTT3[9] = false;
  VITALALL_Y.OUTT3[10] = false;
  VITALALL_Y.OUTT3[11] = false;
  VITALALL_Y.OUTT3[12] = VITALALL_U.DATAFROMZC[33];
  VITALALL_Y.OUTT3[13] = VITALALL_U.DATAFROMZC[41];
  VITALALL_Y.OUTT3[14] = false;
  VITALALL_Y.OUTT3[15] = false;
  VITALALL_Y.OUTT3[16] = VITALALL_U.DATAFROMZC[34];
  VITALALL_Y.OUTT3[17] = VITALALL_U.DATAFROMZC[42];
  VITALALL_Y.OUTT3[18] = false;
  VITALALL_Y.OUTT3[19] = false;
  VITALALL_Y.OUTT3[20] = false;
  VITALALL_Y.OUTT3[21] = false;
  VITALALL_Y.OUTT3[22] = false;
  VITALALL_Y.OUTT3[23] = false;

  /* Outport: '<Root>/OUTDEP' incorporates:
   *  Constant: '<S5>/ZERO'
   */
  VITALALL_Y.OUTDEP[0] = VITALALL_B.VITALMAINLINE_o26;
  VITALALL_Y.OUTDEP[1] = false;
  VITALALL_Y.OUTDEP[2] = false;
  VITALALL_Y.OUTDEP[3] = false;
  VITALALL_Y.OUTDEP[4] = false;
  VITALALL_Y.OUTDEP[5] = false;
  VITALALL_Y.OUTDEP[6] = false;
  VITALALL_Y.OUTDEP[7] = false;
  for (i = 0; i < 6; i++) {
    VITALALL_Y.OUTDEP[i + 8] = VITALALL_B.VITALDEPOT_o20[i];
  }

  VITALALL_Y.OUTDEP[14] = false;
  VITALALL_Y.OUTDEP[15] = false;
  VITALALL_Y.OUTDEP[16] = VITALALL_B.VITALDEPOT_o20[6];
  VITALALL_Y.OUTDEP[17] = VITALALL_B.VITALDEPOT_o20[7];
  VITALALL_Y.OUTDEP[18] = false;
  VITALALL_Y.OUTDEP[19] = false;
  VITALALL_Y.OUTDEP[20] = false;
  VITALALL_Y.OUTDEP[21] = false;
  VITALALL_Y.OUTDEP[22] = false;
  VITALALL_Y.OUTDEP[23] = false;
  VITALALL_Y.OUTDEP[24] = VITALALL_B.VITALDEPOT_o22[0];
  VITALALL_Y.OUTDEP[25] = VITALALL_B.VITALDEPOT_o21[0];
  VITALALL_Y.OUTDEP[26] = VITALALL_B.VITALDEPOT_o22[2];
  VITALALL_Y.OUTDEP[27] = VITALALL_B.VITALDEPOT_o21[2];
  VITALALL_Y.OUTDEP[28] = VITALALL_B.VITALDEPOT_o22[3];
  VITALALL_Y.OUTDEP[29] = VITALALL_B.VITALDEPOT_o21[3];
  VITALALL_Y.OUTDEP[30] = false;
  VITALALL_Y.OUTDEP[31] = false;
  VITALALL_Y.OUTDEP[32] = VITALALL_B.VITALDEPOT_o22[1];
  VITALALL_Y.OUTDEP[33] = VITALALL_B.VITALDEPOT_o21[1];
  VITALALL_Y.OUTDEP[34] = VITALALL_B.VITALDEPOT_o22[1];
  VITALALL_Y.OUTDEP[35] = VITALALL_B.VITALDEPOT_o21[1];
  VITALALL_Y.OUTDEP[36] = false;
  VITALALL_Y.OUTDEP[37] = false;
  VITALALL_Y.OUTDEP[38] = false;
  VITALALL_Y.OUTDEP[39] = false;

  /* End of Outport: '<Root>/OUTDEP' */

  /* Outport: '<Root>/SIMULATION' */
  VITALALL_Y.SIMULATION[0] = VITALALL_B.VITALMAINLINE_o26;
  VITALALL_Y.SIMULATION[9] = VITALALL_B.VITALMAINLINE_o28[0];
  VITALALL_Y.SIMULATION[10] = VITALALL_B.VITALMAINLINE_o28[1];
  for (i = 0; i < 8; i++) {
    VITALALL_Y.SIMULATION[i + 1] = VITALALL_B.VITALMAINLINE_o27[i];
    VITALALL_Y.SIMULATION[i + 11] = VITALALL_B.VITALDEPOT_o20[i];
  }

  VITALALL_Y.SIMULATION[24] = VITALALL_B.VITALDEPOT_o21[0];
  VITALALL_Y.SIMULATION[25] = VITALALL_B.VITALDEPOT_o21[1];
  VITALALL_Y.SIMULATION[26] = VITALALL_B.VITALDEPOT_o21[2];
  VITALALL_Y.SIMULATION[27] = VITALALL_B.VITALDEPOT_o21[3];
  VITALALL_Y.SIMULATION[33] = VITALALL_B.VITALDEPOT_o22[0];
  VITALALL_Y.SIMULATION[34] = VITALALL_B.VITALDEPOT_o22[1];
  VITALALL_Y.SIMULATION[35] = VITALALL_B.VITALDEPOT_o22[2];
  VITALALL_Y.SIMULATION[36] = VITALALL_B.VITALDEPOT_o22[3];
  for (i = 0; i < 5; i++) {
    VITALALL_Y.SIMULATION[i + 19] = VITALALL_B.VITALMAINLINE_o29[i];
    VITALALL_Y.SIMULATION[i + 28] = VITALALL_B.VITALMAINLINE_o30[i];
    VITALALL_Y.SIMULATION[i + 37] = VITALALL_B.VITALMAINLINE_o31[i];
  }

  VITALALL_Y.SIMULATION[42] = VITALALL_B.VITALDEPOT_o23[0];
  VITALALL_Y.SIMULATION[43] = VITALALL_B.VITALDEPOT_o23[1];
  VITALALL_Y.SIMULATION[44] = VITALALL_B.VITALDEPOT_o23[2];
  VITALALL_Y.SIMULATION[45] = VITALALL_B.VITALDEPOT_o23[3];

  /* End of Outport: '<Root>/SIMULATION' */

  /* Outputs for Atomic SubSystem: '<S46>/ROUTE LOGIC' */

  /* Inport: '<Root>/INTIB' incorporates:
   *  Constant: '<S5>/ONE'
   *  Inport: '<Root>/DATAFROMNV'
   *  Inport: '<Root>/DATAFROMZC'
   */
  ROUTE(VITALALL_B.VITALMAINLINE_o27[0], VITALALL_U.INTIB[2], VITALALL_U.INTIB[4],
        true, VITALALL_B.VITALMAINLINE_o5[6], VITALALL_U.DATAFROMNV[134],
        VITALALL_B.VITALMAINLINE_o25[4], VITALALL_U.DATAFROMZC[22],
        (ConstB_ROUTE_T *)&VITALALL_ConstB.ROUTELOGIC_k,
        &VITALALL_DW.ROUTELOGIC_k);

  /* End of Outputs for SubSystem: '<S46>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S47>/ROUTE LOGIC' */
  ROUTE(VITALALL_B.VITALMAINLINE_o27[0], VITALALL_U.INTIB[2], VITALALL_U.INTIB[5],
        VITALALL_U.INTIB[6], VITALALL_B.VITALMAINLINE_o5[17],
        VITALALL_U.DATAFROMNV[134], VITALALL_B.VITALMAINLINE_o25[5],
        VITALALL_U.DATAFROMZC[9], (ConstB_ROUTE_T *)
        &VITALALL_ConstB.ROUTELOGIC_g, &VITALALL_DW.ROUTELOGIC_g);

  /* End of Outputs for SubSystem: '<S47>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S48>/ROUTE LOGIC' */
  ROUTE(VITALALL_B.VITALMAINLINE_o28[0], VITALALL_U.INTIB[2], VITALALL_U.INTIB[5],
        VITALALL_U.INTIB[7], VITALALL_B.VITALMAINLINE_o7[6],
        VITALALL_U.DATAFROMNV[134], VITALALL_B.VITALDEPOT_o19[6],
        VITALALL_U.DATAFROMZC[4], (ConstB_ROUTE_T *)
        &VITALALL_ConstB.ROUTELOGIC_f, &VITALALL_DW.ROUTELOGIC_f);

  /* End of Outputs for SubSystem: '<S48>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S49>/ROUTE LOGIC' */
  ROUTE(VITALALL_B.VITALMAINLINE_o27[2], VITALALL_U.INTIB[2], VITALALL_U.INTIB[4],
        true, VITALALL_B.VITALMAINLINE_o6[0], VITALALL_U.DATAFROMNV[136],
        VITALALL_B.VITALMAINLINE_o25[0], VITALALL_U.DATAFROMZC[14],
        (ConstB_ROUTE_T *)&VITALALL_ConstB.ROUTELOGIC_bt,
        &VITALALL_DW.ROUTELOGIC_bt);

  /* End of Outputs for SubSystem: '<S49>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S51>/ROUTE LOGIC' */
  ROUTE(VITALALL_B.VITALMAINLINE_o27[2], VITALALL_U.INTIB[3], VITALALL_U.INTIB[4],
        true, VITALALL_B.VITALMAINLINE_o6[10], VITALALL_U.DATAFROMNV[136],
        VITALALL_B.VITALMAINLINE_o25[1], VITALALL_U.DATAFROMZC[0],
        (ConstB_ROUTE_T *)&VITALALL_ConstB.ROUTELOGIC_h,
        &VITALALL_DW.ROUTELOGIC_h);

  /* End of Outputs for SubSystem: '<S51>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S52>/ROUTE LOGIC' */

  /* Inport: '<Root>/INT3' incorporates:
   *  Constant: '<S5>/ONE'
   *  Inport: '<Root>/DATAFROMNV'
   *  Inport: '<Root>/DATAFROMZC'
   */
  ROUTE(VITALALL_B.VITALMAINLINE_o27[4], VITALALL_U.INT3[3], VITALALL_U.INT3[4],
        true, VITALALL_B.VITALMAINLINE_o5[20], VITALALL_U.DATAFROMNV[138],
        VITALALL_B.VITALMAINLINE_o25[7], VITALALL_U.DATAFROMZC[13],
        (ConstB_ROUTE_T *)&VITALALL_ConstB.ROUTELOGIC_e,
        &VITALALL_DW.ROUTELOGIC_e);

  /* End of Outputs for SubSystem: '<S52>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S53>/ROUTE LOGIC' */
  ROUTE(VITALALL_B.VITALMAINLINE_o27[6], VITALALL_U.INT3[2], VITALALL_U.INT3[4],
        true, VITALALL_B.VITALMAINLINE_o6[3], VITALALL_U.DATAFROMNV[140],
        VITALALL_B.VITALMAINLINE_o25[2], VITALALL_U.DATAFROMZC[18],
        (ConstB_ROUTE_T *)&VITALALL_ConstB.ROUTELOGIC_c4,
        &VITALALL_DW.ROUTELOGIC_c4);

  /* End of Outputs for SubSystem: '<S53>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S56>/ROUTE LOGIC' */

  /* Inport: '<Root>/INTIB' incorporates:
   *  Inport: '<Root>/DATAFROMNV'
   *  Inport: '<Root>/DATAFROMZC'
   */
  ROUTE(VITALALL_B.VITALMAINLINE_o27[1], VITALALL_U.INTIB[2], VITALALL_U.INTIB[4],
        VITALALL_U.INTIB[6], VITALALL_B.VITALMAINLINE_o5[17],
        VITALALL_U.DATAFROMNV[135], VITALALL_B.VITALMAINLINE_o25[5],
        VITALALL_U.DATAFROMZC[9], (ConstB_ROUTE_T *)
        &VITALALL_ConstB.ROUTELOGIC_l, &VITALALL_DW.ROUTELOGIC_l);

  /* End of Outputs for SubSystem: '<S56>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S58>/ROUTE LOGIC' */
  ROUTE(VITALALL_B.VITALMAINLINE_o27[3], VITALALL_U.INTIB[2], VITALALL_U.INTIB[5],
        VITALALL_U.INTIB[6], VITALALL_B.VITALMAINLINE_o6[0],
        VITALALL_U.DATAFROMNV[137], VITALALL_B.VITALMAINLINE_o25[0],
        VITALALL_U.DATAFROMZC[14], (ConstB_ROUTE_T *)
        &VITALALL_ConstB.ROUTELOGIC_j, &VITALALL_DW.ROUTELOGIC_j);

  /* End of Outputs for SubSystem: '<S58>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S59>/ROUTE LOGIC' */

  /* Inport: '<Root>/INT3' incorporates:
   *  Constant: '<S5>/ONE'
   *  Inport: '<Root>/DATAFROMNV'
   *  Inport: '<Root>/DATAFROMZC'
   */
  ROUTE(VITALALL_B.VITALMAINLINE_o27[5], VITALALL_U.INT3[2], VITALALL_U.INT3[5],
        true, VITALALL_B.VITALMAINLINE_o5[9], VITALALL_U.DATAFROMNV[139],
        VITALALL_B.VITALMAINLINE_o25[6], VITALALL_U.DATAFROMZC[26],
        (ConstB_ROUTE_T *)&VITALALL_ConstB.ROUTELOGIC_jn,
        &VITALALL_DW.ROUTELOGIC_jn);

  /* End of Outputs for SubSystem: '<S59>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S61>/ROUTE LOGIC' */
  ROUTE(VITALALL_B.VITALMAINLINE_o27[5], VITALALL_U.INT3[2], VITALALL_U.INT3[4],
        true, VITALALL_B.VITALMAINLINE_o5[20], VITALALL_U.DATAFROMNV[139],
        VITALALL_B.VITALMAINLINE_o25[7], VITALALL_U.DATAFROMZC[13],
        (ConstB_ROUTE_T *)&VITALALL_ConstB.ROUTELOGIC_o,
        &VITALALL_DW.ROUTELOGIC_o);

  /* End of Outputs for SubSystem: '<S61>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S62>/ROUTE LOGIC' */
  ROUTE(VITALALL_B.VITALMAINLINE_o27[7], VITALALL_U.INT3[3], VITALALL_U.INT3[4],
        true, VITALALL_B.VITALMAINLINE_o6[3], VITALALL_U.DATAFROMNV[141],
        VITALALL_B.VITALMAINLINE_o25[2], VITALALL_U.DATAFROMZC[18],
        (ConstB_ROUTE_T *)&VITALALL_ConstB.ROUTELOGIC_ew,
        &VITALALL_DW.ROUTELOGIC_ew);

  /* End of Outputs for SubSystem: '<S62>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S63>/ROUTE LOGIC' */
  ROUTE(VITALALL_B.VITALMAINLINE_o27[7], VITALALL_U.INT3[2], VITALALL_U.INT3[4],
        true, VITALALL_B.VITALMAINLINE_o6[14], VITALALL_U.DATAFROMNV[141],
        VITALALL_B.VITALMAINLINE_o25[3], VITALALL_U.DATAFROMZC[5],
        (ConstB_ROUTE_T *)&VITALALL_ConstB.ROUTELOGIC_bs,
        &VITALALL_DW.ROUTELOGIC_bs);

  /* End of Outputs for SubSystem: '<S63>/ROUTE LOGIC' */

  /* Outputs for Atomic SubSystem: '<S64>/ROUTE LOGIC' */

  /* Inport: '<Root>/INTIB' incorporates:
   *  Inport: '<Root>/DATAFROMNV'
   *  Inport: '<Root>/DATAFROMZC'
   */
  ROUTE(VITALALL_B.VITALDEPOT_o20[7], VITALALL_U.INTIB[2], VITALALL_U.INTIB[5],
        VITALALL_U.INTIB[7], VITALALL_B.VITALMAINLINE_o8[0],
        VITALALL_U.DATAFROMNV[142], VITALALL_B.VITALMAINLINE_o25[0],
        VITALALL_U.DATAFROMZC[14], (ConstB_ROUTE_T *)
        &VITALALL_ConstB.ROUTELOGIC_n, &VITALALL_DW.ROUTELOGIC_n);

  /* End of Outputs for SubSystem: '<S64>/ROUTE LOGIC' */

  /* Update for Memory: '<S11>/Memory' */
  VITALALL_DW.Memory_PreviousInput[0] = VITALALL_B.VITALDEPOT_o1[0];
  VITALALL_DW.Memory_PreviousInput[1] = VITALALL_B.VITALDEPOT_o1[1];
  VITALALL_DW.Memory_PreviousInput[2] = VITALALL_B.VITALDEPOT_o1[2];
  VITALALL_DW.Memory_PreviousInput[3] = VITALALL_B.VITALDEPOT_o1[3];

  /* Update for ModelReference: '<S11>/VITAL MAINLINE' */
  VITALMAIN_Update();

  /* Update for ModelReference: '<S11>/VITAL DEPOT' */
  VITALDEPOT_Update();

  /* Update absolute time for base rate */
  /* The "clockTick0" counts the number of times the code of this task has
   * been executed. The absolute time is the multiplication of "clockTick0"
   * and "Timing.stepSize0". Size of "clockTick0" ensures timer will not
   * overflow during the application lifespan selected.
   * Timer of this task consists of two 32 bit unsigned integers.
   * The two integers represent the low bits Timing.clockTick0 and the high bits
   * Timing.clockTickH0. When the low bit overflows to 0, the high bits increment.
   */
  if (!(++VITALALL_M->Timing.clockTick0)) {
    ++VITALALL_M->Timing.clockTickH0;
  }

  VITALALL_M->Timing.t[0] = VITALALL_M->Timing.clockTick0 *
    VITALALL_M->Timing.stepSize0 + VITALALL_M->Timing.clockTickH0 *
    VITALALL_M->Timing.stepSize0 * 4294967296.0;

  {
    /* Update absolute timer for sample time: [0.1s, 0.0s] */
    /* The "clockTick1" counts the number of times the code of this task has
     * been executed. The resolution of this integer timer is 0.1, which is the step size
     * of the task. Size of "clockTick1" ensures timer will not overflow during the
     * application lifespan selected.
     * Timer of this task consists of two 32 bit unsigned integers.
     * The two integers represent the low bits Timing.clockTick1 and the high bits
     * Timing.clockTickH1. When the low bit overflows to 0, the high bits increment.
     */
    VITALALL_M->Timing.clockTick1++;
    if (!VITALALL_M->Timing.clockTick1) {
      VITALALL_M->Timing.clockTickH1++;
    }
  }
}

/* Model initialize function */
void VITALALL_initialize(void)
{
  /* Registration code */

  /* initialize real-time model */
  (void) memset((void *)VITALALL_M, 0,
                sizeof(RT_MODEL_VITALALL_T));

  {
    /* Setup solver object */
    rtsiSetSimTimeStepPtr(&VITALALL_M->solverInfo,
                          &VITALALL_M->Timing.simTimeStep);
    rtsiSetTPtr(&VITALALL_M->solverInfo, &rtmGetTPtr(VITALALL_M));
    rtsiSetStepSizePtr(&VITALALL_M->solverInfo, &VITALALL_M->Timing.stepSize0);
    rtsiSetErrorStatusPtr(&VITALALL_M->solverInfo, ((const char_T **)
      (&rtmGetErrorStatus(VITALALL_M))));
    rtsiSetRTModelPtr(&VITALALL_M->solverInfo, VITALALL_M);
  }

  rtsiSetSimTimeStep(&VITALALL_M->solverInfo, MAJOR_TIME_STEP);
  rtsiSetSolverName(&VITALALL_M->solverInfo,"FixedStepDiscrete");
  rtmSetTPtr(VITALALL_M, &VITALALL_M->Timing.tArray[0]);
  VITALALL_M->Timing.stepSize0 = 0.1;

  /* block I/O */
  (void) memset(((void *) &VITALALL_B), 0,
                sizeof(B_VITALALL_T));

  /* states (dwork) */
  (void) memset((void *)&VITALALL_DW, 0,
                sizeof(DW_VITALALL_T));

  /* external inputs */
  (void) memset((void *)&VITALALL_U, 0,
                sizeof(ExtU_VITALALL_T));

  /* external outputs */
  (void) memset((void *)&VITALALL_Y, 0,
                sizeof(ExtY_VITALALL_T));

  {
    static uint32_T *clockTickPtrs[2];
    static uint32_T *clockTickHPtrs[2];
    static real_T *taskTimePtrs[2];
    VITALALL_TimingBrdg.nTasks = 2;
    clockTickPtrs[0] = &(VITALALL_M->Timing.clockTick0);
    clockTickHPtrs[0] = &(VITALALL_M->Timing.clockTickH0);
    clockTickPtrs[1] = &(VITALALL_M->Timing.clockTick1);
    clockTickHPtrs[1] = &(VITALALL_M->Timing.clockTickH1);
    VITALALL_TimingBrdg.clockTick = clockTickPtrs;
    VITALALL_TimingBrdg.clockTickH = clockTickHPtrs;
    taskTimePtrs[0] = &(VITALALL_M->Timing.t[0]);
    taskTimePtrs[1] = (NULL);
    VITALALL_TimingBrdg.taskTime = taskTimePtrs;
  }

  /* Model Initialize fcn for ModelReference Block: '<S11>/VITAL DEPOT' */
  VITALDEPOT_initialize(rtmGetErrorStatusPointer(VITALALL_M),
                        &(VITALALL_M->solverInfo), &VITALALL_TimingBrdg, 0, 1);

  /* Model Initialize fcn for ModelReference Block: '<S11>/VITAL MAINLINE' */
  VITALMAIN_initialize(rtmGetErrorStatusPointer(VITALALL_M),
                       &(VITALALL_M->solverInfo), &VITALALL_TimingBrdg, 0, 1);

  /* Start for ModelReference: '<S11>/VITAL MAINLINE' */
  VITALMAIN_Start();

  /* Start for ModelReference: '<S11>/VITAL DEPOT' */
  VITALDEPOT_Start();

  /* InitializeConditions for ModelReference: '<S11>/VITAL MAINLINE' */
  VITALMAIN_Init();

  /* InitializeConditions for ModelReference: '<S11>/VITAL DEPOT' */
  VITALDEPOT_Init();
}

/* Model terminate function */
void VITALALL_terminate(void)
{
  /* (no terminate code required) */
}

/*
 * File trailer for generated code.
 *
 * [EOF]
 */
